import Head from "next/head";
import Image from "next/image";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="min-h-screen flex flex-1 flex-col justify-center items-center p-8">
				<h1 className="font-bold text-7xl">Jake Hiney</h1>
				<p className="text-center text-2xl p-8 leading-6">
					Financial systems & database analyst, self-taught programmer.
				</p>
				<div className="grid grid-cols-2 gap-6 pt-6">
					<Card />
					<Card />
					<Card />
					<Card />
				</div>
			</div>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer">
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
